title: Deepak Sethi <br/> 
logo: "/images/profile pic.png?raw=true" <br/> 

description: > # your text below (remove <br> elements if you don't need line breaks)
  Deepak Sethi is a seasoned professional with over 5 years of experience in various industries, including hospitality, healthcare, and education.He is currently the working on various independent projects
  <br/>
  <br/>
  Overall, Deepak Sethi is a motivated and accomplished professional with a diverse range of experiences that have prepared him to lead and manage successful ventures in the future. His expertise in business development, marketing, and entrepreneurship, combined with his education and technical skills, make him a valuable asset to any organization.
  <br/>
  <br/>
  <br/>
  <a href="https://www.linkedin.com/in/onlydeepaksethi/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
# google_analytics: 360663342
